---
title: "mini_proj3"
output: 
  html_document:
    code_folding = hide

---

^[https://github.com/hartlegr/macleish]


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(sf)
library(macleish)

```



```{r}
ggplot()+
  geom_sf(data =macleish_layers[["boundary"]]) +
  geom_sf(data =macleish_layers[["trails"]], col = "green") +
  geom_sf(data =macleish_layers[["forests"]]) +
  geom_sf(data =macleish_layers[["streams"]], col = "blue") + 
  geom_sf(data =macleish_layers[["challenge_courses"]], fill = "orange") + 
  geom_sf(data =macleish_layers[["research"]], fill = "orange")+
  geom_sf(data =macleish_layers[["contours_30ft"]], col="red") + 
  geom_sf(data =macleish_layers[["wetlands"]], fill = "yellow") 
  
```


```{r, eval = FALSE}


st_as_sf(macleish_layers) %>% st_transform(3488)

macleish_layers %>%
  pluck("streams") %>%
  st_buffer(dist = 0.1)
```


```{r}
library(leaflet)

base_plot <- leaflet() %>%
  addTiles() %>%
#  addPolylines(data = pluck(macleish_layers, "streams")) %>%
  addPolylines(data = pluck(macleish_layers, "boundary"), col = "black", weight = 3)%>%
  #addPolygons(data = pluck(macleish_layers, "forests"))%>%
#  addPolylines(data = pluck(macleish_layers, "trails"), col = "green")%>%
#  addMarkers(data = pluck(macleish_layers, "challenge_courses"), popup = ~cmt)%>%
#  addPolygons(data = pluck(macleish_layers, "research"), col = "orange")%>%
  addPolygons(data = pluck(macleish_layers, "wetlands"), col = "red", weight = 2)%>%
 # addPolygons(data = pluck(macleish_layers, "contours_30ft"), col = "red")%>%
  addMarkers(lng = -72.678154, lat =  42.450976, popup = "Group Campsite") %>%
  addMarkers(lng = -72.679581, lat = 42.458549, popup = "Remote Campsite") %>%
  addMarkers(lng = -72.680663, lat = 42.448013, popup = "Parking")%>%
  addMarkers(lng = -72.680315, lat = 42.449653, popup = "OrchardMet Weather Station")%>%
  addMarkers(lng = -72.680553, lat = 42.448470, popup = "WhatelyMet Weather Station")

```

```{r}
proj4_aea <- "+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=37.5 +lon_0=-96 +x_0=0 +y_0=0 +ellps=GRS80 +datum=NAD83 +units=m +no_defs"


```

```{r}
stream_buffer <- macleish_layers %>%
  pluck("streams") %>%
  st_transform(proj4_aea) %>%
  st_buffer(dist = 200) %>%
  st_transform(4326)

```




```{r}
parking <- (coords = c( -72.680663, 42.448013)) %>%
 st_as_sf()
```


```{r, eval = FALSE}
parking_buffer <- parking %>%
  st_transform(proj4_aea) %>%
  st_buffer(dist = 200) %>%
  st_transform(4326)
```

```{r}
research_buffer <- macleish_layers %>%
  pluck("research")%>%
  st_transform(proj4_aea)%>%
  st_buffer(dist = 500) %>%
  st_transform(4326)
```

```{r}
challenge_buffer <- macleish_layers %>% 
  pluck("challenge_courses")%>%
  st_transform(proj4_aea)%>%
  st_buffer(dist = 500)%>%
  st_transform(4326)
```

```{r}
forests1 <- macleish_layers%>%
  pluck("forests")%>%
  filter(!is.na(VegType_21))%>%
  group_by(VegType_21)%>%
  summarize(N = n())

```

```{r}
pal <- colorNumeric(
  palette = "inferno", 
  domain = forests1$VegType_21
)
```

```{r}
treeplot <- base_plot %>%
  addPolygons(data = forests1, color = ~pal(VegType_21), weight = 2)

treeplot
```


```{r}
base_plot %>%
  addPolygons(data = stream_buffer)%>%
  addMarkers(lng = -72.679210, lat =  42.444697, popup = "Proposed Site 1", col = "red")%>%
  addMarkers(lng = -72.683844, lat =  42.455057, popup = "Proposed Site 2", col = "red")

 

```

```{r}
  cowIcon <- makeIcon(iconUrl = "http://icons.iconarchive.com/icons/iconsmind/outline/128/Cow-icon.png", iconWidth = 35, iconHeight = 40)

cowIcon <- makeIcon(iconUrl = , iconWidth = 35, iconHeight = 40)
```


```{r}
treeplot %>%
  addMarkers(lng = -72.679210, lat =  42.444697, popup = "Proposed Site 1", icon = cowIcon)%>%
  addMarkers(lng = -72.683844, lat =  42.455057, popup = "Proposed Site 2", icon = greenLeafIcon)

```


```{r}
treeplot %>%
addLegend(map, position = c("bottomright"), pal = qpal, values = ~VegType_21, opacity = 1)
```


```{r}
base_plot%>%
  addMarkers(lng = -72.679210, lat =  42.444697, popup = "Proposed Site 1")%>%
  addMarkers(lng = -72.683844, lat =  42.455057, popup = "Proposed Site 2")%>%
  addPolygons(data = pluck(macleish_layers, "contours_3m"), col = "red")
  

```